---
- name: Deployment Playbook
  hosts: all
  become: yes  # Optional, run tasks with sudo or root privileges

  tasks:
    - name: Run Deployment
      command: " k apply  -f /home/ubuntu/Deployment.yaml"

    - name: Run Service
      command: "k apply -f /home/ubuntu/Service.yaml "