apiVersion: apps/v1
kind: 	Deployment
metadata:
  name: deployment
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: photogenic
  template:
    metadata: 
      name: photopod
      labels:
        app: photogenic
    spec:
      containers:
        - name: photogenicimage
          image: danish84464/pipeline
          ports:
            - name: photoappport
              containerPort: 8080
              protocol: TCP
 
