- name: Deployment Playbook
  hosts: 172.31.15.177
  gather_facts: true

  tasks:
    - name: Install minikube dependencies
      become: true
      apt:
        name: ['curl', 'apt-transport-https', 'virtualbox']

    - name: Install minikube
      become: true
      shell: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

    - name: Start minikube cluster
      become: true
      command: minikube start
      ignore_errors: true

    - name: Apply Deployment
      become: true
      command: kubectl apply -f /home/ubuntu/Deployment.yaml
      args:
        chdir: /home/ubuntu
      register: deployment_result
      ignore_errors: true

    - name: Display Deployment result
      debug:
        var: deployment_result