# apiVersion: v1
# kind: 	Service
# metadata:
#   name:  svc
# spec:
#   selector:
#     matchLabels:
#       app: photogenic
#   ports:
#     - name: svcport
#       port: 80
#       nodePort: 30005
#       targetPort: 80
#   type:  LoadBalancer
